### ISSUE TITLE
Pavex documentation on rustdoc json

### ISSUE THREAD

**Issue by JordanLloydHall** [LukeMathWalker/pavex#106]
The Pavex docs do not mention how to install the Rust core packages docs as JSON.

Running `cargo px build` gave the following error:
```bash
ERROR: 
  × I failed to compute the JSON documentation for one or more crates in the workspace.
  │

Error: `pavex_cli` exited with a non-zero status code: 1
error: Failed to run `bp`, the code generator for package `api_server_sdk`
```

Fixed by running `rustup component add --toolchain nightly rust-docs-json`

Credit to Alona for writing about this here: https://alona.page/posts/rustdoc-json-2022/#:~:text=Making%20this%20work,toolchain%20by%20rustup

**Comment by LukeMathWalker** [comment]
Or, to be more precise, Pavex will automatically add that toolchain given a working installation of `rustup`.

**Comment by LukeMathWalker** [comment]
While we wait for the new amazing installer, this has been fixed in the current docs ✅
