### ISSUE TITLE
Middleware in nested Blueprint reaches unreachable code

### ISSUE THREAD

**Issue by m1guelpf** [LukeMathWalker/pavex#138]
When playing around with my Router, I started reaching an `unreachable!()` spot. Very conveniently, it's not an issue with my very weird code but something that can be replicated in a few lines over the starter kit: https://github.com/m1guelpf/pavex_unreachable_repro/commit/e153691aa9afd1a7885b8f84224c3b71147818a6

```rust
thread 'main' panicked at pavexc/src/compiler/analyses/processing_pipeline/codegen.rs:82:25:
internal error: entered unreachable code
```

**Comment by LukeMathWalker** [comment]
This has been fixed in ebad209f6692f929c331303b7aa27f293b14fe92.
Thanks for reporting it!
