### ISSUE TITLE
Closed beta / Apache license

### ISSUE THREAD

**Issue by maacl** [LukeMathWalker/pavex#249]
I hope this is not a silly question, but what is the meaning of the project being in "closed beta" when it appears to be available here under a Apache V2 License?

**Comment by LukeMathWalker** [comment]
Not silly at all!
To use the current releases as-is you need an activation key, as explained in [the documentation](https://pavex.dev/docs/getting_started/#activation). That activation key is sent out with invites to the private beta, alongside a link to Pavex's private Discord server.

I explain the rationale in reasonable details [here](https://youtu.be/cMea6IMRk2s?si=iwi7wJ_q5MFuV_hJ&t=2841).
