### ISSUE TITLE
Axum & Pavex

### ISSUE THREAD

**Issue by tkr-sh** [LukeMathWalker/pavex#325]
Hello,
I was wondering: what's the point of using Pavex compared to Axum, when one can just use Axum?
What significant advantages does Pavex have?

**Comment by oliverbarnes** [comment]
Hi @tkr-sh, this blog post goes into it in detail: https://www.lpalmieri.com/posts/a-taste-of-pavex-rust-web-framework/

**Comment by LukeMathWalker** [comment]
The blog post linked by Oliver covers a few of the motivating details, and you can find even more material if you look for [my talk on Pavex at Rust Nation UK](https://youtu.be/cMea6IMRk2s?si=vNuWfqMPYtApQ9t8).
