### ISSUE TITLE
Logo proposals

### ISSUE THREAD

**Issue by simonsan** [LukeMathWalker/pavex#37]
![pavex_logo](https://user-images.githubusercontent.com/14062932/230436647-861d1f3f-78d0-4400-8df6-a9c23f88a123.png)

**Comment by LukeMathWalker** [comment]
That looks really cool!
I'm not going to be picking up the logo at this stage, but I'll keep it in mind when we get there 😄

**Comment by LukeMathWalker** [comment]
In the end I decided to go for another design, which is now in the README. Thanks again for sketching one out!
